### ISSUE TITLE
Issues loading CMS configuration

### ISSUE THREAD

**Issue by emmahsax** [weeblrpress/clearstatustheme#5]
Hello.

I've followed the documentation in both the README and the video to a T, but get the following issue when trying to use the Netlify CMS:
![image](https://user-images.githubusercontent.com/7562793/98290803-cb71dd00-1f6f-11eb-9581-3bfe981f635d.png)

I think it's possible that Netlify has changed their CMS configuration so that we need additional settings in one of the `config.yml` files or possibly the `config.md` file.

This is my first time with both Hugo and Netlify, so any help or guidance to fix this would be greatly appreciated. Thanks @weeblr-dev in advance.

Also, there's at least a couple of other people who are having similar issues, so I am not alone. To reproduce, simply start from the beginning of setup with either GitLab or GitHub integrations (I've tested both, and verified that I get the same issues with both).

**Comment by weeblr** [comment]
Hi @emmasax4 

Thanks for reporting, I have seen a few messages about this already but I'm really, really short on time to work on this.

I searched the Netlify CMS git repo and [found the relevant bit](https://github.com/netlify/netlify-cms/issues/4489) (somebody reported the problem directly there).

From a quick look, it seems there's a select widget missing the options list. From what I see looking at ClearStatus, that could happen if:

- The list of **systems** was empty
- The list of **groups** was empty

As grouping is optional, I suspect this is the cause. Netlify was probably accepting this before but it's now an error when that select element is invalid.

I'll try to look more over the weekend.

Cheers

**Comment by clearstatus** [comment]
@emmasax4 Can you try again, I actually looked into it and it seems fixed now. Just trigger a new deploy from your Netlify control panel and that should be enough.

**Comment by emmahsax** [comment]
@clearstatus Yes, that has solved it! Thank you so much everybody! [`3fe548c`](https://github.com/weeblrpress/clearstatustheme/commit/3fe548c468d1ebedff92ffe225fe30760f05c040#diff-cc76c7024a03f145790ab563e8c0a3d20a2017dc40e0614210e30e6874f425f8) seemed to have done the trick.
